# -------------------------------
# MapProxy OMAP configuration.
# -------------------------------
# This is a minimal MapProxy configuration for the ISOM OMAP Ticino Project.
#
# | Version | Modifier   | Date         | Description                               |
# -----------------------------------------------------------------------------------
# | 0.1     | mlanini    | 2023-01-23   | First ever draft.                         |
# | 0.2     | mlanini    | 2023-01-24   | Comprehensive review.                     |
# | 0.3     | mlanini    | 2023-02-01   | Another review.                           |
# |         |            |              |                                           |
# -----------------------------------------------------------------------------------
# 
# Starts the following services:
# WMS:
#     capabilities: http://intelligeo.net/cgi-bin/qgis_mapserv.fcgi?service=WMS&version=1.3.0&request=GetCapabilities


services:
    wmts:
      restful: true
      md:
        title: ISOM_OMAP
        abstract: 'Orienteering basemaps according to ISOM 2017 Ed. 2 symbology specification.'
        online_resource: https://intelligeo.net/cgi-bin/qgis_mapserv.fcgi?version=1.3.0&service=WMS&request=GetCapabilities
        contact:
#          person: Sara Lanini-Maggi
#          position: Owner
#          organization: intelligeo.ch by Sara Lanini-Maggi
#          address: -
#          city: Tegna
#          postcode: 6652
#          state: Ticino
#          country: Switzerland
#          phone: +41 79 262 58 89
          email: basemap@intelligeo.ch
        access_constraints: 'Ask basemap@intelligeo.ch'
        fees: 'None'

    wms:
      md:
        title: ISOM_OMAP
        abstract: 'Orienteering basemaps according to ISOM 2017 Ed. 2 symbology specification.'
        online_resource: https://intelligeo.net/cgi-bin/qgis_mapserv.fcgi?version=1.3.0&service=WMS&request=GetCapabilities
        contact:
#          person: Sara Lanini-Maggi
#          position: Owner
#          organization: intelligeo.ch by Sara Lanini-Maggi
#          address: -
#          city: Tegna
#          postcode: 6652
#          state: Ticino
#          country: Switzerland
#          phone: +41 (0)79 262 58 89
          email: basemap@intelligeo.ch
        access_constraints: 'Ask basemap@intelligeo.ch'
        fees: 'None'

layers:
- name: ISOM_OMAP_Ticino
  title: 'Orienteering Basemap of Canton Ticino - Switzerland'
  md:
    abstract: 'Orienteering basemap of Canton Ticino, Switzerland, based on Open Geospatial Data.'
  sources:
  - omap_wms
  legendurl: http://intelligeo.net/cgi-bin/qgis_mapserv.fcgi?MAP=/home/qgis/projects/omap.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=ISOM_OMAP_Ticino&FORMAT=image/png&WIDTH=250&TRANSPARENT=FALSE&BOXSPACE=2.6&LAYERSPACE=1.3&LAYERTITLESPACE=1.3&SYMBOLSPACE=2.6&ICONLABELSPACE=6.6&SYMBOLWIDTH=6.6&SYMBOLHEIGHT=4&LAYERFONTFAMILY=helvetica&LAYERFONTSIZE=10&LAYERFONTBOLD=TRUE&ITEMFONTFAMILY=helvetica&ITEMFONTSIZE=10

sources:
  omap_wms:
    type: wms
    wms_opts:
      legendgraphic: true
      featureinfo: false
    req:
      url: https://intelligeo.net/cgi-bin/qgis_mapserv.fcgi?version=1.3.0&service=WMS&request=GetCapabilities
      layers: ISOM_OMAP_Ticino
      transparent: true
    supported_srs:
    - EPSG:2056
    - EPSG:3857
    coverage:
      bbox:
      - 2622500.0
      - 1072500.0
      - 2782500.0
      - 1168000.0
      srs: EPSG:2056

caches:
  omap_cache:
    grids:
    - ch95_grid
    - webmercator
    sources:
    - omap_wms

grids:
    webmercator:
      base: GLOBAL_WEBMERCATOR
    
    ch95_grid:
      srs: 'EPSG:2056'
      bbox: [2420000.00,1030000.00,2920000.00,1350000.00]
      origin: nw
      tile_size : [256,256] 
      # resolutions created from scales with        
      res: [4000,2000,1000,500,100,50,20,10,5,2.5,1,0.5,0.25,0.05]

globals:
  cache:
    base_dir: './cache_data'
    lock_dir: './cache_data/locks'
    tile_lock_dir: './cache_data/tile_locks'

  image:
    resampling_method: bicubic # nearest/bilinear
    stretch_factor: 1.15
    max_shrink_factor: 4.0

    # Enable 24bit PNG images.
    paletted: false
    formats:
      custom_format:
        format: image/png
        # the custom format will be stored as 8bit PNG
        mode: P
        colors: 32
        transparent: true
        encoding_options:
        # The algorithm used to quantize (reduce) the image colors
          quantizer: fastoctree
      # edit an existing format
      image/jpeg:
        encoding_options:
          # jpeg quality [0-100]
          jpeg_quality: 85
